---
title: "Das Projekt WZE@Jena"
---

```{r}
#| echo: false
#| warning: false

# load packages
library(leaflet, quietly = TRUE)
library(dplyr)
library(openxlsx)
library(sf)
library(htmltools)

# load spatial objects
load("spatial.objects.jena.Rdata")

# load WZE point locations
# path <- "C:/Users/su28yek/Nextcloud2/11_Projekte/03_WZE@Jena/01_Allgemeine Infos über WZE-Punkte/"
 path <- "D:/Documents/Uni_sync/11_Projekte/03_WZE@Jena/01_Allgemeine Infos über WZE-Punkte/"
wze.lage <- read.xlsx(paste0(path, "Übersicht_WZE-Punkte.xlsx"), sheet = "Lage")
wze.ID <- data.frame(lon = wze.lage$Longitude_WGS84_E, 
                     lat = wze.lage$Latitude_WGS84_N, 
                     WZE_ID = wze.lage$WZE_ID, 
                     Vegtyp_Abk = wze.lage$Vegtyp_Abk,
                     Vegtyp_txt_kurz = wze.lage$Vegtyp_txt_kurz,
                     stringsAsFactors = FALSE)
wze.pt <- st_as_sf(wze.ID, coords = c("lon", "lat"), crs = 4326)
# Create a palette that maps factor levels to colors for Vegtyp_Abk categories
pal <- colorFactor(c("#556B2F", "gold", "#7FFF00", "#00FF7F", "#762a83", "grey30", "brown"), domain = unique(wze.pt$Vegtyp_Abk), ordered = TRUE)
# make legend vector
legend.vector <- paste0("Vegetationstyp: ", wze.ID$Vegtyp_txt_kurz, 
                        "<br>", 
                        "WZE_ID: ", wze.ID$WZE_ID) 
```

Das Projekt **WZE\@Jena** wurde gemeinsam von dem *Institut für Ökologie und Evolution* der Friedrich-Schiller-Universität Jena und dem *Stadtforst Jena* ins Leben gerufen.

```{r}
#| echo: false
#| label: fig-map.jena
#| fig-cap: "Stadtgebiet Jena, bewaldete Flächen in dunkelgrün"
# plot leaflet, OSM
leaflet(wze.pt, height = 700) %>%
  addTiles() %>%
  flyToBounds(lng1 = jena.bbox[1], 
              lat1 = jena.bbox[2], 
              lng2 = jena.bbox[3], 
              lat2 = jena.bbox[4]) %>% 
  setView(lng = 11.59, lat = 50.918, zoom = 12) %>%
  addPolygons(data = jena.border.invers, 
              fillColor = "grey20", fillOpacity = 0.5, 
              stroke = TRUE, color = "black", 
              opacity = 1, weight = 3) %>% 
  addPolygons(data = jena.forest.area, 
              fillColor = "#228B22", fillOpacity = 0.5, 
              stroke = FALSE) %>%  
  addCircleMarkers(label = ~ lapply(legend.vector, HTML),
                   color = "black", opacity = 1, weight = 2,
                   fillColor = ~ pal(Vegtyp_Abk),
                   fillOpacity = 1,
                   stroke = F) %>% 
  addLegend(position = "bottomleft",
            colors = c("#556B2F", "gold", 
                       "#7FFF00", "#00FF7F", 
                       "#762a83", "grey30", "brown"),
            labels = unique(wze.ID$Vegtyp_txt_kurz), 
            opacity = 1,
            title = "Vegetationstypen") %>% 
  fitBounds(lng1 = jena.bbox[1], 
            lat1 = jena.bbox[2],
            lng2 = jena.bbox[3],
            lat2 = jena.bbox[4])

```
