# Karte

```{r}
#| context: setup

# load spatial objects
load("data/spatial.objects.jena.Rdata")

wze.lage <- read.xlsx("data/Übersicht_WZE-Punkte.xlsx", sheet = "Lage")
wze.ID <- data.frame(lon = wze.lage$Longitude_WGS84_E, 
                     lat = wze.lage$Latitude_WGS84_N, 
                     WZE_ID = wze.lage$WZE_ID, 
                     Vegtyp_Abk = wze.lage$Vegtyp_Abk,
                     Vegtyp_txt_kurz = wze.lage$Vegtyp_txt_kurz,
                     stringsAsFactors = FALSE)
wze.pt <- st_as_sf(wze.ID, coords = c("lon", "lat"), crs = 4326)
# Create a palette that maps factor levels to colors for Vegtyp_Abk categories
Vegtyp_Abk.factor <- unique(wze.pt$Vegtyp_Abk) %>% 
  factor(., levels = c("L-WB", "L-OB", "B-Bu", 
                       "L-EH", "B-Mi", "B-Ki", "RE"))
pal <- colorFactor(c("#556B2F", "#7FFF00", "#00FF7F",
                     "gold", "#762a83", "#B3B3B3", "brown"), 
                   domain = Vegtyp_Abk.factor, ordered = TRUE)
# make legend vector
legend.vector <- paste0("Vegetationstyp: ", wze.ID$Vegtyp_txt_kurz, 
                        "<br>", 
                        "WZE_ID: ", wze.ID$WZE_ID) 

```


```{r}
leaflet(wze.pt, height = 800) %>%
  addTiles() %>%
  flyToBounds(lng1 = jena.bbox[1], 
              lat1 = jena.bbox[2], 
              lng2 = jena.bbox[3], 
              lat2 = jena.bbox[4]) %>% 
  setView(lng = 11.59, lat = 50.918, zoom = 12) %>%
  addPolygons(data = jena.border.invers, 
              fillColor = "grey20", fillOpacity = 0.5, 
              stroke = TRUE, color = "black", 
              opacity = 1, weight = 3) %>% 
  addPolygons(data = jena.forest.area, 
              fillColor = "#228B22", fillOpacity = 0.5, 
              stroke = FALSE) %>%  
  addCircleMarkers(label = ~ lapply(legend.vector, HTML),
                   color = "black", opacity = 1, weight = 2,
                   fillColor = ~ pal(Vegtyp_Abk),
                   fillOpacity = 1,
                   stroke = F) %>% 
  addLegend(position = "bottomleft",
            colors = c("#556B2F", "#7FFF00", "#00FF7F",
                     "gold", "#762a83", "#B3B3B3", "brown"),
            labels = unique(wze.ID$Vegtyp_txt_kurz)[c(1,3,4,2,5:7)], 
            opacity = 1,
            title = "Vegetationstypen") %>% 
  fitBounds(lng1 = jena.bbox[1], 
            lat1 = jena.bbox[2],
            lng2 = jena.bbox[3],
            lat2 = jena.bbox[4])

```

